command = "i3status-rs"
font = "JetBrainsMono Nerd Font Mono SemiBold 12"
background = "#00000000"
color = "#ffffffff"
separator = "#666666ff"
tag_fg = "#ffffffff"
tag_bg = "#333333ff"
tag_focused_fg = "#ffffffff"
tag_focused_bg = "#285577ff"
tag_urgent_fg = "#ffffffff"
tag_urgent_bg = "#900000ff"
tag_inactive_fg = "#888888ff"
tag_inactive_bg = "#222222ff"
tags_padding = 8
tags_r = 6
blocks_r = 6
separator_width = 0
height = 24
position = "bottom"
