inactive-opacity = 0.9;
opacity-rule = [
	"90:class_g = 'dmenu'"
];

# Corners
corner-radius = 0;
rounded-corners-exclude = [
	"window_type = 'popup-menu'",
	"window_type = 'tooltip'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'menu'",
	"window_type = 'toolbar'"
];
