function fish_mode_prompt
end
function fish_prompt
    printf '%s%s%s> %s' (set_color facc15) (prompt_pwd) (set_color brred -o) (set_color normal)
end
set -gx PATH $HOME/.cache/.bun/bin $HOME/.bun/bin $HOME/go/bin $HOME/.cargo/bin $HOME/.config/emacs/bin $HOME/.local/bin $PATH

status is-login; and begin
end

status is-interactive; and begin

    # Aliases
    alias cp 'rsync -P'
    alias k kubectl
    alias l 'eza -l --icons'
    alias ls 'eza --icons'
    alias zcp 'rsync --info=progress2 -auvz'

    # Interactive shell initialisation
    fish_default_key_bindings
    fish_config theme choose fish\ default
    zoxide init fish --cmd j | source
    set ZELLIJ_AUTO_ATTACH true

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/ilya/.local/share/fish/home-manager_generated_completions" $post
    end

    # /nix/store/wr9gi46jzk63wff2d0y4m3ngqnraq4p6-direnv-2.36.0/bin/direnv hook fish | source
    direnv hook fish | source

    fastfetch
end

function startw
  # sway --unsupported-gpu
  hyprland
end

function stfd
  poweroff
end
